-- auto-generated definition
create table document
(
    publication_date   date,
    updated_date       date,
    id                 bigint generated by default as identity
        primary key,
    summary_word_count bigint,
    category           varchar(255),
    category_code      varchar(255),
    first_author       varchar(255),
    title              varchar(255),
    authors            varchar(255)[],
    summary            text,
    text               text,
    text_no_stopwords  text
);